FROM node:lts
RUN npm install -g typescript

WORKDIR /backend
COPY ./backend ./

WORKDIR /types
COPY ./types ./
RUN npm ci
RUN npm run prisma

WORKDIR /frontend
COPY ./frontend ./
RUN yarn install --frozen-lockfile

# Environment variables must be present at build time
# https://github.com/vercel/next.js/discussions/14030
ARG ENV_VARIABLE
ENV ENV_VARIABLE=${ENV_VARIABLE}
ARG NEXT_PUBLIC_ENV_VARIABLE
ENV NEXT_PUBLIC_ENV_VARIABLE=${NEXT_PUBLIC_ENV_VARIABLE}
ENV NEXT_TELEMETRY_DISABLED 1
ENV NODE_ENV production

CMD ["yarn", "run", "dev"]