version: '3.8'

services:
  nginx:
    restart: always
    depends_on:
      - frontend
      - backend
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "3555:80"

  backend:
    restart: always
    depends_on:
      - db
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    volumes:
      - repo_data:/repos
    environment:
      - DATABASE_URL=postgres://postgres:example@db:5432/postgres
      - NODE_ENV=production
      - MAX_RUNNING_TASKS=10
      - DOCKER_HOST=unix:///var/run/docker.sock
    privileged: true

  frontend:
    restart: always
    depends_on:
      - backend
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
      args:
        - NODE_ENV=production
        - NEXT_PUBLIC_API_URI=/api

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  db_data:
  repo_data:
