FROM node
RUN npm install -g typescript ts-node

# npm install types
WORKDIR /types
COPY ./types/package.json ./types/package-lock.json ./
RUN npm ci
COPY ./types ./

SHELL ["/usr/bin/env", "node"]
RUN node ./node_modules/prisma/build/index.js generate
SHELL ["/bin/sh", "-c"]

# npm install backend
WORKDIR /backend
COPY ./backend/package.json ./backend/package-lock.json ./
RUN npm ci
RUN cp -r ../types/prisma .

SHELL ["/usr/bin/env", "node"]
RUN  node ./node_modules/prisma/build/index.js generate --schema ./prisma/schema.prisma
SHELL ["/bin/sh", "-c"]

COPY ../backend_config.json ./backend_config.json
COPY ./backend ./

CMD ["sh", "dev.sh"]
