import Head from 'next/head'
import { Inter } from 'next/font/google'
import { CourseOverviewCard } from '@/components';

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Codetierlist</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${inter.className}`}>
        <div className="flex-wrap">
          <CourseOverviewCard name="CSC108" image="https://placehold.co/300x200" session='F' ></CourseOverviewCard>
          <CourseOverviewCard name="CSC207" image="https://placehold.co/300x200" session='W' ></CourseOverviewCard>
        </div>
      </main>
    </>
  )
}
