import Head from 'next/head';
import {Inter} from 'next/font/google';
import {CourseOverviewCard} from '@/components';
import {UserContext} from "@/contexts/UserContext";
import {useContext, useState} from "react";
import {
    Button,
    Dialog,
    DialogActions,
    DialogBody,
    DialogContent, DialogOpenChangeData, DialogOpenChangeEvent,
    DialogSurface,
    DialogTitle,
    DialogTrigger,
    Input,
    Label
} from "@fluentui/react-components";
import axios from "@/axios";

const inter = Inter({subsets: ['latin']});

function CreateCourseForm({closeDialog}: { closeDialog: () => void }) {
    const [courseCode, setCourseCode] = useState("");
    const [courseName, setCourseName] = useState("");
    const {fetchUserInfo} = useContext(UserContext);
    return (
        <DialogSurface>
            <DialogBody>
                <form onSubmit={(e) => {
                    e.preventDefault();
                    axios.post("/courses", {
                        code: courseCode,
                        name: courseName
                    }).then(fetchUserInfo).then(closeDialog);
                }}>
                    <DialogTitle>Create Course</DialogTitle>
                    <DialogContent>
                        <Label htmlFor="courseCode">Course Code:</Label><br/>
                        <Input type="text" id="courseCode" name="courseCode"
                            value={courseCode}
                            onChange={e => setCourseCode(e.target.value)}/><br/>
                        <Label htmlFor="courseName">Course Name:</Label><br/>
                        <Input type="text" id="courseName" name="courseName"
                            value={courseName}
                            onChange={e => setCourseName(e.target.value)}/><br/><br/>
                    </DialogContent>
                    <DialogActions>
                        <DialogTrigger disableButtonEnhancement>
                            <Button appearance="secondary">Close</Button>
                        </DialogTrigger>
                        <Button type="submit"
                            appearance="primary">Create</Button>
                    </DialogActions>
                </form>
            </DialogBody>
        </DialogSurface>
    );
}

export default function Home() {
    const {userInfo} = useContext(UserContext);
    const [showDialog, setShowDialog] = useState(false);
    return (
        <>
            <Head>
                <title>Codetierlist</title>
                <meta name="description"
                    content="Generated by create next app"/>
                <meta name="viewport"
                    content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <main className={`${inter.className}`}>
                {userInfo.admin ?
                    <Dialog open={showDialog} onOpenChange={(e:DialogOpenChangeEvent, data: DialogOpenChangeData) => setShowDialog(data.open)}>
                        <DialogTrigger disableButtonEnhancement>
                            <Button>Create Course</Button>
                        </DialogTrigger>
                        <CreateCourseForm closeDialog={()=>setShowDialog(false)}/>
                    </Dialog>
                    : undefined}
                <div className="flex-wrap">
                    {userInfo.roles.map(x => x.course).map(x => (
                        // TODO session probably shouldn't be hardcoded, image placeholder should be replaced with actual course image
                        <CourseOverviewCard key={x.id} id={x.id} name={x.code}
                            image="https://placehold.co/300x200"
                            session={"Fall"}></CourseOverviewCard>
                    ))}
                </div>
            </main>
        </>
    );
}
