on:
  push:
    branches:
      - dev
  workflow_dispatch:
jobs:
  deploy:
    runs-on: dev
    steps:
      - uses: actions/checkout@v2

      - name: create env files
        run: |
          echo "${{ secrets.REDIS_PASSWORD }}" > ./redis/.env;

      - name: compose build
        run: DOCKER_BUILDKIT=0 docker compose build
      - name: compose build runners
        run: DOCKER_BUILDKIT=0 docker compose -f docker-compose-runner.yml build

      - name: compose up
        run: DOCKER_BUILDKIT=0 docker compose up -d
      - name: compose up runners
        run: DOCKER_BUILDKIT=0 docker compose -f docker-compose-runner.yml up -d
